## 건물정보와 가점척도를 읽어 건물1, 건물2, ... 등으로 분리

### 1. 읽어들일 파일명 지정 ==> 가지고 있는 파일명으로 수정필요

In [1]:
########### file_name 선언 ##################################
건물셋 = r'C:\miniprj\실습데이터\전처리결과\건물_위경도.csv'
가점척도 = r'C:\miniprj\실습데이터\건물가점_전처리.csv'
결과파일 = r'C:\miniprj\실습데이터\전처리결과\건물N.csv'
#############################################################

### 2. 이하 수정 금지

In [2]:
import pandas as pd

건물 = pd.read_csv(f'{건물셋}', header=0, encoding='cp949', engine='python')
가점 = pd.read_csv(f'{가점척도}', header=0, encoding='cp949', engine='python')
건물.rename(columns = {'BDTYP_CD':'건물용도코드'},inplace = True)
건물.rename(columns = {'BUL_MAN_NO':'건물일련번호'},inplace = True)
display(건물.head(2))
display(가점.head(2))

,건물용도코드,BD_MGT_SN,BSI_INT_SN,BSI_ZON_NO,BULD_MNNM,BULD_NM,BULD_NM_DC,BULD_SE_CD,BULD_SLNO,BUL_DPN_SE,...,NTFC_DE,OPERT_DE,POS_BUL_NM,RDS_MAN_NO,RDS_SIG_CD,RN_CD,SIG_CD,UND_FLO_CO,lon,lat
0,3199,4825025026103190133016795,41165,50859,6,NaN,NaN,0,0,M,...,20171211.0,2.018012e+13,NaN,807,48250,4805739,48250,0,128.722863,35.320180
1,1001,4825037024107140000000001,79067,50809,167,NaN,NaN,0,8,M,...,20170206.0,2.017031e+13,NaN,2770,48250,4805274,48250,0,128.958495,35.249866

   건물용도코드     건물종류  가점척도
0   17201  가축용운동시설     0
1   17204    가축용창고     0

In [4]:
merged = 건물.merge(가점, on='건물용도코드')
merged = merged.rename(columns={'lon': '경도', 'lat': '위도'})
merged = merged[['건물용도코드', '건물종류', '건물일련번호', '가점척도', '경도', '위도']]
merged.head(2)

   건물용도코드    건물종류  건물일련번호  가점척도          경도         위도
0    3199  기타공공시설  118853     1  128.722863  35.320180
1    1001    단독주택  115761     0  128.958495  35.249866

In [5]:
가점갯수 = len(merged['가점척도'].unique())
bd = [None] * 가점갯수

for i in range(가점갯수):
    bd[i] = merged[merged['가점척도']==i]    
    bd[i].to_csv(결과파일.replace('N', f'{i}'), 
                 index=False, sep=',', encoding='cp949')
    display (bd[i].iloc[[0]])
for i in range(가점갯수):
    print (f"{i}점 건물수:",len(bd[i]))

   건물용도코드  건물종류  건물일련번호  가점척도          경도         위도
1    1001  단독주택  115761     0  128.958495  35.249866

   건물용도코드    건물종류  건물일련번호  가점척도          경도        위도
0    3199  기타공공시설  118853     1  128.722863  35.32018

    건물용도코드 건물종류  건물일련번호  가점척도          경도         위도
54   16001  주차장  127619     2  128.840141  35.208692

      건물용도코드  건물종류  건물일련번호  가점척도          경도         위도
3016    7101  종합병원  115750     3  128.869611  35.256703

0점 건물수: 55348
1점 건물수: 43079
2점 건물수: 2934
3점 건물수: 187

In [6]:
bd

[        건물용도코드       건물종류  건물일련번호  가점척도          경도         위도
 1         1001       단독주택  115761     0  128.958495  35.249866
 7         7108        요양소  117731     0  128.753426  35.239515
 9         1001       단독주택  118943     0  128.789046  35.177748
 10       17203        관리사  188078     0  128.806546  35.358792
 11        1003      다가구주택  118910     0  128.790492  35.178100
 ...        ...        ...     ...   ...         ...        ...
 101515   17999  기타동식물관련시설  189519     0  128.873962  35.191295
 101527   17999  기타동식물관련시설  189562     0  128.777330  35.179378
 101529   17203        관리사  188898     0  128.845846  35.195374
 101540   17203        관리사  189038     0  128.868405  35.179771
 101541   17203        관리사  188938     0  128.986089  35.248810

 [55348 rows x 6 columns],
         건물용도코드    건물종류  건물일련번호  가점척도          경도         위도
 0         3199  기타공공시설  118853     1  128.722863  35.320180
 2        13100    일반공장  115780     1  128.765716  35.265629
 3        13100    일반공장  115781     1  128.766098  35.265707
 4        13100    일반공장  115910     1  128.769113  35.272296
 5        13100    일반공장  115911     1  128.769144  35.272576
 ...        ...     ...     ...   ...         ...        ...
 101535    3002   휴게음식점  189541     1  128.779697  35.182874
 101538   13100    일반공장  188989     1  128.988713  35.274971
 101539   13100    일반공장  188990     1  128.989067  35.275133
 101546   13100    일반공장  188878     1  128.986466  35.274563
 101547   13100    일반공장  188879     1  128.986719  35.274673

 [43079 rows x 6 columns],
         건물용도코드 건물종류  건물일련번호  가점척도          경도         위도
 54       16001  주차장  127619     2  128.840141  35.208692
 116      16001  주차장  124718     2  128.883484  35.233933
 150      16001  주차장  112091     2  128.863523  35.227244
 177       2001  아파트  119771     2  128.883418  35.226944
 178       2001  아파트  119772     2  128.883909  35.226983
 ...        ...  ...     ...   ...         ...        ...
 101537    2001  아파트  188979     2  128.872091  35.256965
 101542    2001  아파트  188981     2  128.870767  35.256402
 101543    2001  아파트  188982     2  128.871278  35.256427
 101544    2001  아파트  188984     2  128.871280  35.257018
 101545    2001  아파트  188988     2  128.873460  35.256837

 [2934 rows x 6 columns],
         건물용도코드       건물종류  건물일련번호  가점척도          경도         위도
 3016      7101       종합병원  115750     3  128.869611  35.256703
 4637      6203      대형판매점  157842     3  128.838758  35.235166
 6011      6203      대형판매점     969     3  128.870262  35.241904
 6012      6203      대형판매점     970     3  128.869437  35.241583
 6013      6203      대형판매점     971     3  128.869147  35.241586
 ...        ...        ...     ...   ...         ...        ...
 94608     6203      대형판매점  108997     3  128.900949  35.226458
 94612     6203      대형판매점  109001     3  128.882049  35.225546
 99455     6203      대형판매점  112305     3  128.804691  35.191919
 99477     4023  복합유통.제공업소  112851     3  128.734474  35.313002
 100850    6203      대형판매점  135138     3  128.984789  35.236265

 [187 rows x 6 columns]]

끝