In [1]:
전처리데이터 = r'D:\미니프로젝트\실습데이터\전처리결과\전처리데이터.csv'
격자위경도 = r'D:\미니프로젝트\실습데이터\전처리결과\격자_위경도.csv'
결과파일 = r'D:\미니프로젝트\실습데이터\전처리결과\김해_전처리데이터셋.csv'

In [2]:
import pandas as pd

df = pd.read_csv(f'{전처리데이터}', header=0, encoding='cp949', engine='python')
df2 = pd.read_csv(f'{격자위경도}', header=0, encoding='cp949', engine='python')

display(df.head(2))
display(df2.head(2))

,gid,건물1,건물2,건물3,행정기관,도서관,주차구획수_sum,경제인구,전기차와충전소_전처리_결과_전기차,전기차와충전소_전처리_결과_충전소,김해_차량평균속도_avg_speed
0,마라09ab99bb,0,0,0,0,0,NaN,NaN,0,0,NaN
1,마라09ba98ba,0,0,0,0,0,NaN,NaN,0,0,NaN

          gid         lon        lat
0  마라09ab99bb  128.702814  35.288404
1  마라09ba98ba  128.705396  35.277108

In [3]:
df['행정기관'] = df['행정기관'] + df['도서관']
del df['도서관']

In [4]:
df.rename(columns = {'행정기관':'관공서'},inplace = True)
df.rename(columns = {'주차구획수_sum':'주차장'},inplace = True)
df.rename(columns = {'전기차와충전소_전처리_결과_전기차':'전기차'},inplace = True)
df.rename(columns = {'전기차와충전소_전처리_결과_충전소':'충전소'},inplace = True)
df.rename(columns = {'김해_차량평균속도_avg_speed':'차량속도'},inplace = True)

display(df.head(2))

          gid  건물1  건물2  건물3  관공서  주차장  경제인구  전기차  충전소  차량속도
0  마라09ab99bb    0    0    0    0  NaN   NaN    0    0   NaN
1  마라09ba98ba    0    0    0    0  NaN   NaN    0    0   NaN

In [5]:
df = df.merge(df2, on='gid')
display(df.head(2))

,gid,건물1,건물2,건물3,관공서,주차장,경제인구,전기차,충전소,차량속도,lon,lat
0,마라09ab99bb,0,0,0,0,NaN,NaN,0,0,NaN,128.702814,35.288404
1,마라09ba98ba,0,0,0,0,NaN,NaN,0,0,NaN,128.705396,35.277108

In [6]:
df.to_csv(f'{결과파일}', index=False, sep=',', encoding='cp949')