In [1]:
충전소정보 = r'C:\miniprj\실습데이터\전처리결과\충전소정보_격자.csv'
결과파일 = r'C:\miniprj\실습데이터\전처리결과\김해_충전량현황종합_전처리.csv'

In [2]:
import pandas as pd

# CSV 불러오기
df = pd.read_csv(f'{충전소정보}', encoding='cp949')

In [3]:
# 1~9월 충전량 컬럼과 이용수(횟수) 컬럼 목록
충전량_cols = [f'2023년 0{i}월 충전량' for i in range(1, 10)]
이용수_cols = [f'2023년 0{i}월 충전횟수' for i in range(1, 10)]

In [4]:
# 총합 계산
df['총충전량'] = df[충전량_cols].sum(axis=1)
df['총이용수'] = df[이용수_cols].sum(axis=1)

# 일수 계산 (2023년 1~9월은 평년 기준)
월별_일수 = [31, 28, 31, 30, 31, 30, 31, 31, 30]  # 2023년은 윤년 아님
총일수 = sum(월별_일수)

# 일평균 계산
df['일평균충전량'] = df['총충전량'] / 총일수
df['일평균이용수'] = df['총이용수'] / 총일수

In [5]:
df

,충전소명,충전소 주소,대분류,소분류,충전소ID,충전기ID,충전기타입,충전용량,충전방식(단독_동시),충전기상태,...,2023년 08월 충전량,2023년 09월 충전횟수,2023년 09월 충전량,LAT,LON,gid,총충전량,총이용수,일평균충전량,일평균이용수
0,장유(서부산) 휴게소,경상남도 김해시 장유로116번길 44-82 (부곡동),휴게시설,고속도로 휴게소,ME178125,1,DC차데모+AC3상+DC콤보,급속(50kW),단독,사용가능,...,586.95,29,427.60,35.212465,128.793845,마라17bb91ba,16259.41,1036,59.558278,3.794872
1,장유(서부산) 휴게소,경상남도 김해시 장유로116번길 44-82 (부곡동),휴게시설,고속도로 휴게소,ME178125,2,DC차데모+AC3상+DC콤보,급속(50kW),단독,사용가능,...,3296.70,243,3949.41,35.212465,128.793845,마라17bb91ba,27368.69,1839,100.251612,6.736264
2,롯데마트 장유점,경상남도 김해시 번화1로56번길 15 롯데마트,상업시설,마트(쇼핑몰),ME178157,1,DC차데모+AC3상+DC콤보,급속(50kW),단독,사용가능,...,1784.31,84,1755.50,35.193038,128.801298,마라18ab89ab,17044.62,956,62.434505,3.501832
3,롯데마트 김해점,경상남도 김해시 김해대로 2330 (부원동),상업시설,마트(쇼핑몰),ME181228,1,DC차데모+AC3상+DC콤보,급속(50kW),단독,사용가능,...,786.99,73,763.22,35.225546,128.882049,마라25bb93aa,7466.94,636,27.351429,2.329670
4,김해금관가야(기장) 휴게소,경상남도 김해시 대동면 월촌리 770,휴게시설,고속도로 휴게소,ME183209,1,DC차데모+AC3상+DC콤보,급속(100kW동시),단독,사용가능,...,4260.63,311,4697.74,35.268229,129.002795,마라36ba98aa,37079.74,2543,135.823223,9.315018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,유하공원공영주차장,경상남도 김해시 무계동 169-1,주차시설,공영주차장,ME22C1I8,1,DC콤보,급속(100kW단독),단독,사용가능,...,0.00,0,0.00,35.205657,128.809137,마라19aa90bb,4.75,2,0.017399,0.007326
63,지내동공단 공영주차장,경상남도 김해시 지내동 195-20,주차시설,공영주차장,ME22C225,1,DC콤보,급속(100kW단독),단독,사용가능,...,0.00,2,1.54,35.226382,128.922396,마라29ab93ab,8.52,5,0.031209,0.018315
64,지내동공단 공영주차장,경상남도 김해시 지내동 195-20,주차시설,공영주차장,ME22C225,2,DC콤보,급속(100kW단독),단독,사용가능,...,0.00,2,2.71,35.226382,128.922396,마라29ab93ab,9.00,5,0.032967,0.018315
65,김해문화의전당,경상남도 김해시 내동 1131,교육문화시설,공연장,ME22C229,1,DC콤보,급속(100kW단독),단독,사용가능,...,0.00,0,0.00,35.243656,128.869900,마라24ba95aa,5.68,3,0.020806,0.010989
66,김해문화의전당,경상남도 김해시 내동 1131,교육문화시설,공연장,ME22C229,2,DC콤보,급속(100kW단독),단독,사용가능,...,0.00,0,0.00,35.243656,128.869900,마라24ba95aa,5.49,3,0.020110,0.010989

In [9]:
# 필요한 컬럼만 추출
result_df = df[['충전소명','마지막 충전시작일시','마지막 충전종료일시','총충전량','총이용수','일평균충전량','일평균이용수','LON','LAT','gid']].copy()

In [10]:
result_df

,충전소명,마지막 충전시작일시,마지막 충전종료일시,총충전량,총이용수,일평균충전량,일평균이용수,LON,LAT,gid
0,장유(서부산) 휴게소,2023/10/30,2023/10/30,16259.41,1036,59.558278,3.794872,128.793845,35.212465,마라17bb91ba
1,장유(서부산) 휴게소,2023/10/30,2023/10/30,27368.69,1839,100.251612,6.736264,128.793845,35.212465,마라17bb91ba
2,롯데마트 장유점,2023/10/29,2023/10/29,17044.62,956,62.434505,3.501832,128.801298,35.193038,마라18ab89ab
3,롯데마트 김해점,2023/10/30,2023/10/30,7466.94,636,27.351429,2.329670,128.882049,35.225546,마라25bb93aa
4,김해금관가야(기장) 휴게소,2023/10/30,2023/10/30,37079.74,2543,135.823223,9.315018,129.002795,35.268229,마라36ba98aa
...,...,...,...,...,...,...,...,...,...,...
62,유하공원공영주차장,2023/10/29,2023/10/29,4.75,2,0.017399,0.007326,128.809137,35.205657,마라19aa90bb
63,지내동공단 공영주차장,2023/10/30,2023/10/30,8.52,5,0.031209,0.018315,128.922396,35.226382,마라29ab93ab
64,지내동공단 공영주차장,2023/10/30,2023/10/30,9.00,5,0.032967,0.018315,128.922396,35.226382,마라29ab93ab
65,김해문화의전당,2023/10/30,2023/10/30,5.68,3,0.020806,0.010989,128.869900,35.243656,마라24ba95aa
66,김해문화의전당,2023/10/30,2023/10/30,5.49,3,0.020110,0.010989,128.869900,35.243656,마라24ba95aa

In [11]:
result_df.to_csv(f'{결과파일}', index=False, sep=',', encoding='cp949')